### PR TITLE
add usage documentation

### PR DESCRIPTION
**Pull request by hainam8x**
Add documentation.
I still do not understand the usage of Posting and Cost Center to write the documentation.
- What is the difference between Journal and Posting. Is posting just mean 1 line in Journal?
- Is the cost center is applied to Posting only?

### CODE REVIEW

**Comment by ledermann** [comment]
Great, thanks for you work!

Regarding your questions:

- A `Journal` consists of two (at least) `Postings`. Another word for `Journal` may be "Accounting Record". A `Journal` does not belong to an `Account`, but a `Posting` does.
- Yes, a `Cost Center` can be applied to a `Posting` only - because the `Posting` is the thing which belongs to an `Account` and has an `amount`.

**Comment by ledermann** [comment]
Fixes #2

**Comment by jesster2k10** [comment]
Hey, has the documentation been published? I'd like to learn more about the library but it's pretty hard to without digging around the source code (which is tedious)

**Comment by ledermann** [comment]
No, not merged yet. There is a new PR, see #12

**Pull request closed without merging**
